info:
  namespace: iasurvival
items:
  cassiterite_ore:
    enabled: true
    display_name: display-name-cassiterite_ore
    permission: iasurvival.items.cassiterite_ore
    resource:
      material: PAPER
      generate: true
      textures:
        - block/ores/cassiterite_ore
    specific_properties:
      block:
        hardness: 3
        placed_model:
          type: REAL_NOTE
          break_particles_material: COAL_ORE
        cancel_drop: true
        break_tools_blacklist:
          - WOODEN_PICKAXE
          - STONE_PICKAXE
        break_tools_whitelist:
          - PICKAXE
          - pickaxe
          - _hammer
