info:
  namespace: iasurvival
items:
  dark_amethyst_ore:
    enabled: true
    display_name: display-name-dark_amethyst_ore
    permission: iasurvival.items.dark_amethyst_ore
    resource:
      material: PAPER
      generate: true
      textures:
        - block/ores/dark_amethyst_ore
    specific_properties:
      block:
        hardness: 4
        placed_model:
          type: REAL_NOTE
          break_particles_material: COAL_ORE
        cancel_drop: true
        break_tools_blacklist:
          - WOODEN_PICKAXE
          - STONE_PICKAXE
        break_tools_whitelist:
          - PICKAXE
          - pickaxe
          - _hammer
