info:
  namespace: iasurvival
font_images:
  thirst_bar_positive:
    suggest_in_command: false
    path: hud/thirst_bar/positive
    y_position: -15
  thirst_bar_negative:
    suggest_in_command: false
    path: hud/thirst_bar/negative
    y_position: -15
  thirst_bar_half:
    suggest_in_command: false
    path: hud/thirst_bar/half
    y_position: -15
huds:
  thirst_bar:
    enabled: true
    show:
      auto: true
      creative: false
      underwater: false
      riding: false
    type: STATUS
    x_position_pixels: 10
    direction: LEFT
    value:
      player_stat_name: thirst
      start: 10
      min: 0
      max: 10
      triggers:
        decrement:
          generic_over_time_60_minutes_inside:
            min_sky_light: 0
            max_sky_light: 13
            every_ticks: 72000
            amount: 0.5
          generic_over_time_45_minutes_outside:
            min_sky_light: 14
            max_sky_light: 15
            every_ticks: 54000
            amount: 0.5
          biome_over_time_desert_30_minutes_outside:
            min_sky_light: 14
            max_sky_light: 15
            biome: DESERT
            every_ticks: 36000
            amount: 0.5
          food_level_change:
            amount: 0.1
        increment:
          food_level_change:
            amount: 0.1
          player_respawn:
            amount: 10
        on_min_value:
          damage_player:
            every_ticks: 100
            damage: 0.5
          potion_effect:
            every_ticks: 100
            type: SLOW
            amplifier: 1
            duration: 100
    images:
      positive: iasurvival:thirst_bar_positive
      half: iasurvival:thirst_bar_half
      negative: iasurvival:thirst_bar_negative
