info:
  namespace: iasurvival
items:
  coffee:
    enabled: true
    display_name: display-name-coffee
    permission: iasurvival.items.coffee
    resource:
      material: POTION
      generate: true
      textures:
        - item/thirst/coffee
    specific_properties:
      potion:
        type: WATER
        color: WHITE
    item_flags:
      - HIDE_POTION_EFFECTS
    events:
      drink:
        increment_player_stat:
          name: thirst
          amount: 2
        potion_effect:
          type: SPEED
          amplifier: 1
          duration: 100
        give_item:
          item: empty_cup
          amount: 1
