info:
  namespace: iasurvival
items:
  modern_stone:
    enabled: true
    display_name: display-name-modern_stone
    permission: iasurvival.decorative.modern_stone
    resource:
      material: PAPER
      generate: true
      textures:
        - block/decorative/modern_stone
    specific_properties:
      block:
        placed_model:
          type: REAL_NOTE
          break_particles_material: COBBLESTONE
        break_tools_whitelist:
          - PICKAXE
          - pickaxe
