info:
  namespace: iasurvival
  dictionary-lang: th
dictionary:
  display-name-dark_amethyst_helmet: หมวกแอเมทิสต์เข้ม
  display-name-dark_amethyst_chestplate: เสื้อเกราะแอเมทิสต์เข้ม
  display-name-dark_amethyst_leggings: เลกกิ้งแอเมทิสต์เข้ม
  display-name-dark_amethyst_boots: รองเท้าบูทแอเมทิสต์เข้ม
  display-name-bronze_helmet: หมวกสำริด
  display-name-bronze_chestplate: เสื้อเกราะสำริด
  display-name-bronze_leggings: เลกกิ้งสำริด
  display-name-bronze_boots: รองเท้าบูทสำริด
  display-name-emerald_helmet: หมวกมรกต
  display-name-emerald_chestplate: เสื้อเกราะมรกต
  display-name-emerald_leggings: เลกกิ้งมรกต
  display-name-emerald_boots: รองเท้าบูทมรกต
  display-name-obsidian_helmet: หมวกออบซิเดียน
  display-name-obsidian_chestplate: เสื้อเกราะออบซิเดียน
  display-name-obsidian_leggings: เลกกิ้งออบซิเดียน
  display-name-obsidian_boots: รองเท้าบูทออบซิเดียน
  display-name-ruby_helmet: หมวกทับทิม
  display-name-ruby_chestplate: เสื้อเกราะทับทิม
  display-name-ruby_leggings: เลกกิ้งทับทิม
  display-name-ruby_boots: รองเท้าบูททับทิม
  display-name-modern_quartz: แร่ควอร์ซสมัยใหม่
  display-name-modern_sandstone: หินทรายสมัยใหม่
  display-name-modern_stone: หินสมัยใหม่
  display-name-nice_stone: หินสภาพดี
  display-name-nice_wood: ไม้สภาพดี
  display-name-dark_amethyst_block: บล็อกแอเมทิสต์เข้ม
  display-name-dark_amethyst_prism_block: บล็อกปริซิมแอเมทิสต์เข้ม
  display-name-aqua_aura_block: บล็อกแร่อะควา ออร่า
  display-name-crystal_block: บล็อกคริสตัล
  display-name-ruby_block: บล็อกทับทิม
  display-name-spinel_block: บล็อกสปิเนล
  display-name-turquoise_block: บล็อกแร่เทอร์คอยซ์
  display-name-black_bow: ธนูย้อมสีดำ
  display-name-red_bow: ธนูย้อมสีแดง
  display-name-green_bow: ธนูย้อมสีเขียว
  display-name-blue_bow: ธนูย้อมสีน้ำเงิน
  display-name-purple_bow: ธนูย้อมสีม่วง
  display-name-cyan_bow: ธนูย้อมสีฟ้า
  display-name-tomato_seeds: เมล็ดมะเขือเทศ
  display-name-garlic_seeds: เมล็ดกระเทียม
  display-name-lettuce_seeds: เมล็ดผักกาด
  display-name-chili_pepper_seeds: เมล็ดพริก
  display-name-rice_seeds: เมล็ดข้าว
  display-name-tobacco_seeds: เมล็ดยาสูบ
  display-name-black_moor_goldfish: ปลาทองพันธุ์เล่ห์
  display-name-blue_parrotfish: ปลานกแก้วสีน้ำเงิน
  display-name-cod_nigiri: ปลาคอดนิกิริ
  display-name-cooked_black_moor_goldfish: ปลาทองพันธุ์เล่ห์ปรุงสุก
  display-name-cooked_blue_parrotfish: ปลานกแก้วสีน้ำเงินปรุงสุก
  display-name-cooked_goldfish: ปลาคอดนิกิริปรุงสุก
  display-name-cooked_green_sunfish: ปลาพระอาทิตย์สีเขียวปรุงสุก
  display-name-cooked_tuna: ปลาทูน่าปรุงสุก
  display-name-goldfish: ปลาทอง
  display-name-green_sunfish: ปลาพระอาทิตย์สีเขียว
  display-name-pufferfish_nigiri: ปลาปักเป้านิกิริ
  display-name-salmon_nigiri: ปลาแซลมอนนิกิริ
  display-name-tropical_fish_nigiri: ปลาเขตร้อนนิกิริ
  display-name-tuna: ปลาทูน่า
  display-name-baguette: บาเก็ต
  display-name-broken_egg: ไข่แตก
  display-name-cheese: ชีส
  display-name-chili_powder: พริกป่น
  lore-1-chili_powder: '&7ได้รับจาก'
  lore-2-chili_powder: '&7พริก'
  display-name-chips: มันฝรั่งทอด
  display-name-cooked_donut_base: แป้งโดนัทปรุงสุก
  display-name-cooked_sausage: ไส้กรอกปรุงสุก
  display-name-donut_base: แป้งโดนัท
  display-name-dough: แป้งโด
  display-name-flour: แป้ง
  display-name-french_fries: เฟรนช์ฟราย
  display-name-fried_egg: ไข่ทอด
  display-name-fried_potato_sticks: แท่งมันฝรั่งทอด
  display-name-hamburger: แฮมเบอร์เกอร์
  display-name-hotdog: ฮ็อทดอก
  display-name-jar: ขวดโหล
  display-name-sweet_berries_jam_jar: ขวดโหลแยมเบอรี่หวาน
  display-name-pear_jam_jar: ขวดโหลแยมลูกแพร์
  display-name-apple_jam_jar: ขวดโหลแยมแอปเปิ้ล
  display-name-ketchup: ซอสมะเขือเทศ
  lore-1-ketchup: '&7ได้รับจาก'
  lore-2-ketchup: '&7ขวดซอสมะเขือเทศ'
  display-name-ketchup_bottle: ขวดซอสมะเขือเทศ
  lore-1-ketchup_bottle: '&7ไว้บนโต๊ะประดิษฐ์งาน'
  lore-2-ketchup_bottle: '&7ช่องกลางเพื่อจะได้รับ'
  lore-3-ketchup_bottle: '&7ซอสมะเขือเทศ'
  display-name-nether_donut: โดนัทโลกวิญญาณ
  display-name-peeled_potato: มันฝรั่งปอกเปลือกแล้ว
  display-name-pink_donut: โดนัทสีชมพู
  display-name-pizza: พิซซ่า
  display-name-potato_sticks: แท่งมันฝรั่ง
  display-name-sausage: ไส้กรอก
  display-name-sliced_baguette: บาเก็ตหั่น
  display-name-sliced_bread: ขนมปังหั่น
  display-name-sliced_bread_with_apple_jam: ขนมปังหั่นกับแยมแอปเปิ้ล
  display-name-sliced_bread_with_pear_jam: ขนมปังหั่นกับแยมลูกแพร์
  display-name-sliced_bread_with_sweet_berries_jam: ขนมปังหั่นกับแยมเบอรี่หวาน
  display-name-sliced_cheese: ชีสหั่น
  display-name-sliced_raw_beef: เนื้อวัวหั่น
  display-name-sliced_roast_beef: เนื้อวัวย่างหั่น
  display-name-sweet: หวาน
  display-name-sweet_stick: แท่งขนมหวาน
  display-name-taco: ทาโก้
  display-name-banana: กล้วย
  display-name-chili_pepper: พริก
  display-name-garlic: กระเทียม
  display-name-lettuce: ผักกาด
  display-name-pear: ลูกแพร์
  display-name-rice: ข้าว
  display-name-tomato: มะเขือเทศ
  display-name-customization_table: โต๊ะสำหรับการกำหนดเอง
  display-name-restoration_table: โต๊ะการฟื้นฟู
  display-name-dark_amethyst: แอเมทิสต์เข้ม
  display-name-dark_amethyst_ore: แร่แอเมทิสต์เข้ม
  display-name-dark_amethyst_prism: ปริซึมแอเมทิสต์เข้ม
  display-name-aqua_aura: อะควา ออร่า
  display-name-aqua_aura_ore: แร่อะควา ออร่า
  display-name-blaze_powder_ore: แร่พลังเพลิง
  display-name-bronze_ingot: ก้อนสำริด
  display-name-raw_tin: ดีบุกดิบ
  display-name-raw_tin_and_copper_ingot_dust: ผงแร่ดีบุกดิบและก้อนทองแดง
  display-name-cassiterite: แคสซิเทอไรด์
  display-name-cassiterite_block: บล็อกแคสซิเทอไรด์
  display-name-cassiterite_fragment: เศษแคสซิเทอไรด์
  display-name-cassiterite_ore: แร่แคสซิเทอไรด์
  display-name-coal_dirt_ore: แร่ดินถ่านหิน
  display-name-coal_nugget: ก้อนถ่านหิน
  display-name-crystal: คริสตัล
  display-name-end_crystals: คริสตัลเอนด์
  display-name-end_ingot: ก้อนแร่เอนด์
  display-name-end_ore: แร่เอนด์
  display-name-end_shard: เศษแร่เอนด์
  display-name-forgotten_crying_obsidian: '&9ออบซิเดียนร่ำไห้ที่ถูกลืม'
  display-name-fossil: ฟอสซิล
  display-name-gold_dirt_ore: แร่ดินทอง
  display-name-iron_dirt_ore: แร่ดินเหล็ก
  display-name-knowledge_fragment: เศษความรู้
  display-name-ruby: ทับทิม
  display-name-ruby_ore: แร่ทับทิม
  display-name-spinel: สปิเนล
  display-name-spinel_ore: แร่สปิเนล
  display-name-turquoise: เทอร์คอยซ์
  display-name-turquoise_ore: แร่เทอร์คอยซ์
  display-name-dark_amethyst_shield: โล่แอเมทิสต์เข้ม
  display-name-bronze_shield: โล่สำริด
  display-name-ender_shield: โล่เอนเดอร์
  display-name-obsidian_shield: โล่ออบซิเดียน
  display-name-ruby_shield: โล่ทับทิม
  display-name-dark_amethyst_sword: ดาบแอเมทิสต์เข้ม
  display-name-aqua_sword: ดาบอะควา ออร่า
  display-name-bronze_sword: ดาบสำริด
  display-name-crystal_sword: ดาบคริสตัล
  display-name-end_sword: ดาบเอนด์
  display-name-knife: มีด
  display-name-ruby_dagger: มีดทับทิม
  display-name-ruby_sword: ดาบทับทิม
  display-name-aqualight_sword: Aqualight
  display-name-bloodnite_sword: Bloodnite
  display-name-emerald_sword: ดาบมรกต
  display-name-firesword_sword: Firesword
  display-name-rusteroth_sword: Rusteroth
  display-name-vyderlight_sword: Vyderlight
  display-name-sweets_sword: ดาบขนมหวาน
  display-name-turquoise_sword: ดาบเทอร์คอยซ์
  display-name-bloody_mary: บลัดดี้ แมร่
  display-name-coffee: กาแฟ
  display-name-cola: โคล่า
  display-name-cup_of_hot_water: แก้วน้ำร้อน
  display-name-cup_of_water: แก้วน้ำดื่ม
  display-name-drink_glass: แก้วเครื่องดื่ม
  display-name-empty_cup: แก้วน้ำว่างเปล่า
  display-name-hot_chocolate: ช็อคโกแลตร้อน
  display-name-boiled_water_bucket: ถังน้ำเดือด
  display-name-waterskin: ถุงใส่น้ำ
  display-name-dark_amethyst_axe: ขวานแอเมทิสต์เข้ม
  display-name-dark_amethyst_hoe: จอบแอเมทิสต์เข้ม
  display-name-dark_amethyst_pickaxe: อีเตอร์แอเมทิสต์เข้ม
  display-name-dark_amethyst_shovel: พลั่วแอเมทิสต์เข้ม
  display-name-bronze_axe: ขวานสำริด
  display-name-bronze_hoe: จอบสำริด
  display-name-bronze_pickaxe: อีเตอร์สำริด
  display-name-bronze_shovel: พลั่วสำริด
  display-name-chisel: สิ่ว
  display-name-black_shears: กรรไกรย้อมดำ
  display-name-red_shears: กรรไกรย้อมแดง
  display-name-green_shears: กรรไกรย้อมเขียว
  display-name-blue_shears: กรรไกรย้อมสีน้ำเงิน
  display-name-purple_shears: กรรไกรย้อมม่วง
  display-name-cyan_shears: กรรไกรย้อมสีฟ้า
  display-name-diamond_hammer: '&3&lค้อนเพชร'
  display-name-black_fishing_rod: เบ็ดตกปลาย้อมดำ
  display-name-red_fishing_rod: เบ็ดตกปลาย้อมแดง
  display-name-green_fishing_rod: เบ็ดตกปลาย้อมเขียว
  display-name-blue_fishing_rod: เบ็ดตกปลาย้อมสีน้ำเงิน
  display-name-purple_fishing_rod: เบ็ดตกปลาย้อมม่วง
  display-name-cyan_fishing_rod: เบ็ดตกปลาย้อมสำฟ้า
  display-name-ruby_axe: ขวานทับทิม
  display-name-ruby_hoe: จอบทับทิ
  display-name-ruby_pickaxe: อีเตอร์ทับทิ
  display-name-ruby_shovel: พลั่วทับทิ
  display-name-letter: จดหมาย
  display-name-nest: รังนก
  display-name-eggs_nest: รังนกมีไข่
  display-name-plastic: พลาสติก
  display-name-plastic_plate: จานพลาสติก
  display-name-iron_plate: จานเหล็ก
  display-name-tobacco: ยาสูบ
  lore-1-end_sword: '&6[ &eเอฟเฟกต์พิเศษ &6]'
  lore-2-end_sword: '&7โจมตีศัตรูรอบ ๆ ไปด้วย'
  display-name-sword_skin_rusteroth: "สกินดาบ Rusteroth"
  display-name-sword_skin_bloodnite: "สกินดาบ Bloodnite"
  display-name-sword_skin_vyderlight: "สกินดาบ Vyderlight"
  display-name-sword_skin_aqualight: "สกินดาบ Aqualight"
