info:
  namespace: iasurvival
items:
  sliced_bread_with_pear_jam:
    enabled: true
    display_name: display-name-sliced_bread_with_pear_jam
    permission: iasurvival.various.sliced_bread_with_pear_jam
    resource:
      material: COOKED_PORKCHOP
      generate: true
      textures:
        - item/food/various/sliced_bread_with_pear_jam
    events:
      eat:
        feed:
          amount: 5
          saturation: 1
