info:
  namespace: iaalchemy
items:
  mysterious_book:
    enabled: true
    display_name: display-name-mysterious_book
    permission: iaalchemy.items.mysterious_books.mysterious_book
    resource:
      material: WRITTEN_BOOK
      generate: true
      textures:
        - item/mysterious_book
    specific_properties:
      book:
        author: ...
        generation: TATTERED
        pages:
          - >-
            &kThis is a super secret message, hidden in this &rforgotten book...
            You won't be able to know &kwhat's the &rsecret of &kour
            organization...
          - >-
            ?????????????????????????????????????????????????????????????????????????????
          - >-
            ?????????????????????????????????????????????????????????????????????????????
          - >-
            ?????????????????????????????????????????????????????????????????????????????
          - >-
            ?????????????????????????????????????????????????????????????????????????????
          - >-
            ?????????????????????????????????????????????????????????????????????????????
  mysterious_book_decrypted:
    enabled: true
    display_name: display-name-mysterious_book_decrypted
    permission: iaalchemy.items.mysterious_books.mysterious_book_decrypted
    resource:
      material: WRITTEN_BOOK
      generate: true
      textures:
        - item/mysterious_book_decrypted
    specific_properties:
      book:
        author: Hooded figure
        generation: ORIGINAL
        pages:
          - >-
            &8This is a super secret message, hidden in this &rforgotten book...
            You won't be able to know &8what's the &rsecret of &8our
            organization...
          - >-
            We've hidden a lot of artifacts and rare minerals all over the world
            before disappearing... but not every member of us is dead, remember
            this.
